# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: php:7.2
# hitalos/laravel:latest
# image: samueldebruyn/debian-git
image: dotsunited/git-ftp
pipelines:
  branches:
    master:
      - step:
          # max-time: 4
          deployment: production
          script:
            # - apt-get update
            # - apt-get -qq install git-ftp
            # - git config git-ftp.url "ftp://master.suneducationgroup.com:8021"
            # - git config git-ftp.user "$FTP_USERNAME"
            # - git config git-ftp.password "$FTP_PASSWORD"
            # - git ftp init
             - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://master.suneducationgroup.com:8021 -vv
#            - git ftp push --user $P_FTP_USERNAMES --passwd $P_FTP_PASSWORDS ftp://54.169.116.71/
